version: '3.1'

services:

    db:
        image: postgres
        restart: always
        ports:
            - 5555:5432
        environment:
            POSTGRES_DB: qw_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080